### ISSUE TITLE
Front doladění

### ISSUE THREAD

**Issue by tsusanka** [Clevis/ClevisArticles#1]
@enzy koukám, že jsi se na to už vrhnul, je to velmi pěkné :). Ještě bych navrhoval:
- dodat texy nápovědu, jako je to na NajdiProstory 
  ![selection_001](https://f.cloud.github.com/assets/1835345/828279/dd0e8b4e-f0b0-11e2-82db-1cfeea626439.png)
  ![selection_002](https://f.cloud.github.com/assets/1835345/828281/eae68ab4-f0b0-11e2-8d82-af6a10d100ab.png)
  viz [NajdiProstory](https://github.com/Clevis/NajdiProstory/tree/master/app/AdminModule/templates/partials)
- změnit poměry sloupců v datagridu (rozšířit sloupec pro titulky a např. zmenšit ten pro "viditelnost")
- hodit někam (do editace?) odkaz na článek (tj. na Front:Articles:)

co myslíš?

**Comment by enzy** [comment]
Ten datagrid se styluje hrozně špatně, nejlépe bych ho zrušil úplně.

**Comment by tsusanka** [comment]
:) proto jsem se ptal - máš nějaký návrh? klidně tam hoďme něco jiného

**Comment by enzy** [comment]
třeba jen foreach? :D

**Comment by tsusanka** [comment]
hehe klidně, je to na tobě :P. Tak mam zahodit ten datagrid a jen to tam vydumpovat?

**Comment by enzy** [comment]
Asi jo, to bude nejuniverzálnější :)

**Comment by tsusanka** [comment]
Tak je to pryč, jen jsem to tam vypsal, tak je to na tobě :).
